<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="LibraryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="Id" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="author" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="genre" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Book_BookRecord" Member="BookRecords" ThisKey="Id" OtherKey="book_id" Type="BookRecord" />
      <Association Name="Book_InventoryState" Member="InventoryStates" ThisKey="Id" OtherKey="Book_id" Type="InventoryState" />
    </Type>
  </Table>
  <Table Name="dbo.BookRecord" Member="BookRecords">
    <Type Name="BookRecord">
      <Column Name="Id" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="book_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Book_BookRecord" Member="Book" ThisKey="book_id" OtherKey="Id" Type="Book" IsForeignKey="true" />
      <Association Name="Customer_BookRecord" Member="Customer" ThisKey="customer_id" OtherKey="Id" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Id" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Customer_BookRecord" Member="BookRecords" ThisKey="Id" OtherKey="customer_id" Type="BookRecord" />
    </Type>
  </Table>
  <Table Name="dbo.InventoryState" Member="InventoryStates">
    <Type Name="InventoryState">
      <Column Name="Book_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Available" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Book_InventoryState" Member="Book" ThisKey="Book_id" OtherKey="Id" Type="Book" IsForeignKey="true" />
    </Type>
  </Table>
</Database>